### ISSUE TITLE
1panel

### ISSUE THREAD

**Issue by devhaozi** [cxzx150133/not-open-source#10]
仓库地址: https://github.com/1Panel-dev/1Panel
开源许可证: GPL
理由: 部分开源，专业版xpack部分不开源且发布版本与仓库编译产物不一致

**Comment by cxzx150133** [comment]
首先，感谢你的 issue，请原谅我的处理速度（咕咕咕

关于**部分开源**，我感觉不能这么算，因为专业版功能是**相对独立且可选的**，**社区版的功能似乎足以支撑 Linux 面板这样一个产品的基本使用**，所以如果就社区版开源这个角度来看，好像看不出什么问题。

关于 xpack，我对 Golang 不太熟，xpack 我从 gitignore 中可以看到被忽略了，但是具体有什么功能文档中似乎并未提及，简单看了下没看出明显的依赖关系。

不过我发现了项目介绍很奇怪的一点：

1. README 非中文(简体)的情况，**未提及存在专业版这回事**，这里应该算是存在误导，默认的 dev 分支项目默认的 README 甚至没有中文的 README 的入口。
2. 我翻了下 README 和项目信息里预留的项目主页 <https://1panel.hk/>，文档中似乎也没有提及有专业版这回事，中文 README 专业版介绍链接指向 <https://www.lxware.cn/1panel>，这边倒是有提及，但是真的很难找。

因此思考再三，我决定暂时先以 **存在未明确提及的不开源版本(专业版)** 理由加上去，后面再将这种社区版开源，专业版不开源的项目单独列出来。（因为正常情况下如果划分了两个版本，社区版开源了，专业版按照一般的认知来说应该是闭源的 ，不然划分的意义就没那么大了。另外社区版开源，专业版闭源这种商业模式本身其实挺好的，对于优秀的软件，应予以支持和鼓励。）

（话说飞致云的产品细究下怎么感觉开源开的都有点问题。

在 2024 年的末尾，祝新年快乐！
---
2025 年，如果有机会，我打算试着做一套工具，用于检测仓库中是否存在未知/可疑的部分，这样的话理论上后面处理类似问题应该能快很多，也能基于客观事实避免主观臆断，不过考虑到现实情况的奇葩程度，哪怕有 AI 辅助要实现这种检测应该都有不小的挑战。
